// This is a Javascript test harness that simulates the execution of Lambda function code

var MyLambdaFunction = require('../src/index.js'); // assumes single Lambda function with exports.handler

var context = {};
var event =  // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
    {
        "session": {
            "new": true,
                "sessionId": "session1234",
                "attributes": {},
            "user": {
                "userId": null
            },
            "application": {
                "applicationId": "amzn1.echo-sdk-ams.app.[unique-value-here]"
            }
        },
        "version": "1.0",
        "request": {
        "type": "LaunchRequest",
            "requestId": "request5678"
        }
    };


function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}
// call the function
MyLambdaFunction['handler'] (event, context, callback);

